### ISSUE TITLE
`LICENSE` file looks broken

### ISSUE THREAD

**Issue by yasuo-ozu** [OpenWaseda/kemuide#10]
Title only.

```
file LICENSE
LICENSE: gzip compressed data, last modified: Mon Nov 28 10:26:01 2016, from Unix, original size modulo 2^32 3983360
```

**Comment by yasuo-ozu** [comment]
It should be a text file and containing MIT license articles copyrighted to the OpenWaseda contributors.

**Comment by hikalium** [comment]
Right. Could you make a p-r for this?

**Comment by hikalium** [comment]
or of course, you can commit the change directly.
